### ISSUE TITLE
【2022.2 版本不支持，所以才会出问题】 1.2.5 bug 提交

### ISSUE THREAD

**Issue by qiuji10** [AkiKurisu/AkiBT#1]
当在Node里选择SharedVariable时，尽管在BlackBoard有了对应特性的变量但是还是出现了错误

![image](https://user-images.githubusercontent.com/74701224/217408521-6c22760f-f4c7-4f46-9cf4-7e359b7a78c5.png)

已保存Blackboard但是变量没有出现
![image](https://user-images.githubusercontent.com/74701224/217408706-9df7889f-e53e-47b8-9cda-2ae6ab365c60.png)

Console 里出现的错误
ArgumentException: Default value  is not present in the list of possible values
UnityEngine.UIElements.PopupField`1[T]..ctor (System.String label, System.Collections.Generic.List`1[T] choices, System.String defaultValue, System.Func`2[T,TResult] formatSelectedValueCallback, System.Func`2[T,TResult] formatListItemCallback) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.DropdownField..ctor (System.String label, System.Collections.Generic.List`1[T] choices, System.String defaultValue, System.Func`2[T,TResult] formatSelectedValueCallback, System.Func`2[T,TResult] formatListItemCallback) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
Kurisu.AkiBT.Editor.SharedVariableField`2[T,K].OnToggle (System.Boolean IsShared) (at Assets/Plugins/AkiBT/Editor/Core/Member/Field/SharedVariableField.cs:61)
Kurisu.AkiBT.Editor.SharedVariableField`2[T,K].<.ctor>b__8_0 (UnityEngine.UIElements.ChangeEvent`1[T] evt) (at Assets/Plugins/AkiBT/Editor/Core/Member/Field/SharedVariableField.cs:30)
UnityEngine.UIElements.EventCallbackFunctor`1[TEventType].Invoke (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.PropagationPhase propagationPhase) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventCallbackRegistry.InvokeCallbacks (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.PropagationPhase propagationPhase) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase evt) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.CallbackEventHandler.UnityEngine.UIElements.IEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEventAcrossPropagationPath (UnityEngine.UIElements.EventBase evt) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatchUtilities.PropagateEvent (UnityEngine.UIElements.EventBase evt) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.DefaultDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <084a5ad0c5954e6381efa8c13e0e5fac>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <cc8d1d098f6847c2a2db0ea6e317e088>:0)

**Comment by AkiKurisu** [comment]
可以告诉我你使用的Node是为BuiltIn的Node吗，如果能够提供一下编辑器版本更好，因为我使用2021.3.12没有出现该问题，这样我可以复现一下Bug。

**Comment by qiuji10** [comment]
ah 可能是因为我用的版本是 2022.2 的，所以是我这边的问题

**Comment by AkiKurisu** [comment]
我刚使用了2022.2.2，发现UIElement部分APi进行了升级，可能会导致无法使用（我这里甚至出现了Crash），建议使用2021版本
