### ISSUE TITLE
例子里钩选了 Exposed 的话，会导致节点树被清空

### ISSUE THREAD

**Issue by Lead-NorthStar** [AkiKurisu/AkiBT#13]
![图片](https://github.com/user-attachments/assets/af84828e-61c4-44dd-b7ed-d55523e4f44f)
如果钩选了 Exposed 的话，会运行到下图里，然后导致节点树被清空。
![图片](https://github.com/user-attachments/assets/a8a09e42-1861-4be1-a095-0c18657f0476)

**Comment by AkiKurisu** [comment]
已修复 aeb51dd7eb5bd9824bce7ce718217f5081f37433

**Comment by Lead-NorthStar** [comment]
谢谢
