### ISSUE TITLE
Sample是不是过时了

### ISSUE THREAD

**Issue by linrealp** [AkiKurisu/AkiBT#4]
我直接下的release包1.4.4版本，我导入Unity，会报错。可能是函数已经发生变化了？
![image](https://github.com/AkiKurisu/AkiBT/assets/44330725/19383a10-4908-4f64-a6e5-81c257f5f6d1)

**Comment by AkiKurisu** [comment]
感谢提醒，示例确实忘记了更新。

- 1.4.4移除了`InitVariable`的手动绑定方式，全部用反射绑定共享变量，你可以先注释掉。
- `BehaviorTreeBuilder `可以参考https://github.com/AkiKurisu/AkiBT/blob/main/Runtime/Core/Model/BehaviorTreeBuilder.cs

**Comment by linrealp** [comment]
好的，辛苦大佬
